pipeline {
     agent any 
        
        
        
        environment {
        bucket = "sam-jenkins-demo-us-west-2-rana-ziauddin"          //artifact deployment S3 buckets 
        bucket1 = "sam-jenkins-demo-us-east-2-ranaziauddin"         //artifact upload s3 bucket 
        region = "us-east-1"                     //artifact deployment bucket region 
        region1 = "us-east-2"                    //artifact upload bucket region 
        aws_credential = "AWSReservedSSO_AdministratorAccess_564bcbbbca5e5655/rzdin@enquizit.com" //aws credentials 
        application_name = "Nodejs" 
        DOCKERHUB_CREDENTIALS = "rzdin-dockerhub"
        
           
        
       
       
    }
       tools { 
                     maven 'maven' 
                     jdk 'JAVA_HOME' 
   }
    stages {
        stage('Build') {
             
            steps {
                sh 'mvn -B -DskipTests clean package -Dv=${BUILD_NUMBER}'
            }
        }
        stage('Test') {
              
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }

          stage('docker image build/push') {
             
            steps {
                 script{
                 
                    docker.withRegistry( 'https://index.docker.io/v1/',  DOCKERHUB_CREDENTIALS ) {
                    def app = docker.build("rzdin/my-java-app:${BUILD_NUMBER}", '.').push()
                    }           
           }
        }
     }
  }
}
